// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ant-col-rtl': string;
  'components-form-demo-normal-login': string;
  'form-wrapper': string;
  'login-form': string;
  'login-form-button': string;
  'login-form-forgot': string;
}
export const cssExports: CssExports;
export default cssExports;
